gameworn/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from allauth.account.decorators import secure_admin_login
from django.views.generic.base import TemplateView

admin.autodiscover()
# admin.site.login = secure_admin_login(admin.site.login)

urlpatterns = [
    path("", include("memorabilia.urls")),
    path("accounts/", include("allauth.urls")),
    path("accounts/profile/", TemplateView.as_view(template_name="profile.html")),
    path('admin/', admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    urlpatterns = [
        *urlpatterns,
        path("__reload__/", include("django_browser_reload.urls")),
    ] + debug_toolbar_urls()

memorabilia/urls.py
from django.urls import path, include
from . import views

app_name = "memorabilia"
urlpatterns = [
    path("", views.home, name="home"),
    path("search", views.search_collectibles, name="search_collectibles"),
    path('accounts/', include('allauth.urls')),
    path("collection/create", views.create_collection, name="create_collection"),
    path("collection/", views.IndexView.as_view(), name="list_collections"),
    path("collection/<int:pk>/", views.CollectionView.as_view(), name="collection"),
    path("collection/<int:collection_id>/edit", views.edit_collection, name="edit_collection"),
    path("collection/<int:collection_id>/delete", views.delete_collection, name="delete_collection"),
    path("collection/<int:collection_id>/collectible/create", views.create_collectible, name="create_collectible"),
    path("collection/<int:collection_id>/collectible/<int:pk>", views.CollectibleView.as_view(), name="collectible"),
    path("collection/<int:collection_id>/collectible/<int:collectible_id>/edit", views.edit_collectible, name="edit_collectible"),
    path("collection/<int:collection_id>/collectible/<int:collectible_id>/delete", views.delete_collectible, name="delete_collectible"),
    path("collection/<int:collection_id>/collectible/bulk-edit", views.bulk_edit_collectibles, name="bulk_edit_collectibles"),
    path("collection/<int:collection_id>/collectible/<int:collectible_id>/photoMatch/create", views.create_photo_match, name="create_photo_match"),
    path("collection/<int:collection_id>/collectible/<int:collectible_id>/photoMatch/<int:pk>", views.PhotoMatchView.as_view(), name="photo_match"),
    path("collection/<int:collection_id>/collectible/<int:collectible_id>/photoMatch/<int:photo_match_id>/edit", views.edit_photo_match, name="edit_photo_match"),
    path("collection/<int:collection_id>/collectible/<int:collectible_id>/photoMatch/<int:photo_match_id>/delete", views.delete_photo_match, name="delete_photo_match"),
    path("external/flickr/album", views.get_flickr_album, name="get_flickr_album"),
    path("external/flickr/albums/<str:username>/<str:album>", views.get_flickr_albums, name="get_flickr_albums"),
    path("resources", views.ExternalResourceListView.as_view(), name="list_externalresources"),
    path("api/teams", views.get_teams, name="get_teams"),
]

memorabilia/models.py
from django.utils.timezone import now
from django.db import models
from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from rules.contrib.models import RulesModel
import rules

from django_flowbite_widgets.flowbite_fields import FlowbiteImageDropzoneModelField


# Create your models here.
@rules.predicate(bind=True)
def is_collection_owner(self, user, collection):
    if self.context.args:
        return user.id == collection.owner_uid
    return False


@rules.predicate(bind=True)
def is_collectible_owner(self, user, collectible):
    if self.context.args:
        # print(user.id)
        # print(collectible.collection.owner_uid)
        return user.id == collectible.collection.owner_uid
    return False


class Collection(RulesModel):
    owner_uid = models.IntegerField()
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images', blank=True, null=True)
    image_link = models.CharField(max_length=255, blank=True, null=True)
    last_updated = models.DateTimeField(default=now, editable=False)

    class Meta:
        rules_permissions = {
            'create': rules.is_authenticated,
            'update': rules.is_authenticated & is_collection_owner,
            'delete': rules.is_authenticated & is_collection_owner
        }

    def __str__(self):
        return self.title

    # @admin.display(
    #         boolean = True,
    #         ordering="pub_date",
    #         description="Published recently?"
    # )


class ExternalResource(RulesModel):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    link = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.title


class WantedItem(RulesModel):
    title = models.CharField(max_length=100)
    league = models.CharField(max_length=5)
    player = models.CharField(max_length=100)
    season = models.CharField(max_length=10, blank=True, null=True)
    game_type = models.CharField(max_length=25)
    description = models.CharField(max_length=500)
    usage_type = models.CharField(max_length=5)

    def __str__(self):
        return self.title


class Collectible(RulesModel):
    title = models.CharField(max_length=100)
    league = models.CharField(max_length=5)
    brand = models.CharField(max_length=25)
    size = models.CharField(max_length=5)
    player = models.CharField(max_length=100)
    team = models.CharField(max_length=150, blank=True, null=True)
    number = models.IntegerField(blank=True, null=True)
    season = models.CharField(max_length=10)
    game_type = models.CharField(max_length=5)
    description = models.CharField(max_length=500)
    usage_type = models.CharField(max_length=5)
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    for_sale = models.BooleanField(blank=True, null=True)
    for_trade = models.BooleanField(blank=True, null=True)
    asking_price = models.FloatField(blank=True, null=True)
    looking_for = models.ForeignKey(WantedItem, on_delete=models.CASCADE, blank=True, null=True)
    last_updated = models.DateTimeField(default=now, editable=False)


    class Meta:
        rules_permissions = {
            'create': rules.is_authenticated & is_collection_owner,
            'update': rules.is_authenticated & is_collectible_owner,
            'delete': rules.is_authenticated & is_collectible_owner
        }


    def get_primary_image(self):
        primary_image_filter = self.images.filter(primary=True)
        # print(primary_image_filter)
        if len(primary_image_filter) >= 1:
            # print(primary_image_filter[0])
            if primary_image_filter[0].image:
                return primary_image_filter[0].image
            elif primary_image_filter[0].link:
                return primary_image_filter[0].link
        else:
            images = self.images.all()
            if len(images) >= 1:
                primary_image = images[0].image
                return primary_image
        return None

    def __str__(self):
        return self.title


class CollectibleImage(RulesModel):
    collectible = models.ForeignKey(Collectible, on_delete=models.CASCADE, related_name='images')
    primary = models.BooleanField(blank=True, null=True)
    image = models.ImageField(upload_to='images', blank=True, null=True)
    link = models.CharField(max_length=255, blank=True, null=True)
    flickrObject = models.TextField(blank=True, null=True)


class PhotoMatch(RulesModel):
    image = models.ImageField(upload_to='images', blank=True, null=True)
    link = models.CharField(max_length=255, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    game_date = models.DateField()
    collectible = models.ForeignKey(Collectible, on_delete=models.CASCADE, related_name='photomatches')

    class Meta:
        rules_permissions = {
            'create': rules.is_authenticated & is_collectible_owner,
            'update': rules.is_authenticated & is_collectible_owner,
            'delete': rules.is_authenticated & is_collectible_owner
        }

    def __str__(self):
        return '%s %s' % (self.collectible.title, self.game_date)


class League(models.Model):
    key = models.CharField(max_length=5, primary_key=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class UsageType(models.Model):
    key = models.CharField(max_length=5, primary_key=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class GameType(models.Model):
    key = models.CharField(max_length=5, primary_key=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Team(models.Model):
    name = models.CharField(max_length=150)
    league = models.ForeignKey(League, to_field='key', on_delete=models.CASCADE)

    class Meta:
        unique_together = ("name", "league")

    def __str__(self):
        return f"{self.name} ({self.league_id})"

memorabilia/templates/memorabilia/collectible_card.html
<div class="mx-auto w-full md:w-2/5 xl:w-1/4">
    <a href="{{ link }}">
        <div class="flex flex-col">
            {% if image %}
            <img class="h-auto w-full rounded-lg" alt="{{ label }}" src="{{ image }}" />
            {% endif %}
            <div class="text-2xl font-medium text-center text-gray-800 w-full text-center">{{ label }}</div>    
        </div>
    </a>
</div>

memorabilia/templates/memorabilia/collectible_detail.html
{% extends 'memorabilia/base.html' %}
{% load memorabilia_extras %}

{% block page_navigation %}
    {% if user.is_authenticated %}
        {% if user.id == object.collection.owner_uid or user.is_superuser %}
            {% url 'memorabilia:edit_collectible' object.collection.id object.id as the_url %}
            {% include "memorabilia/navitem.html" with link=the_url label="Edit Collectible" %}

            {% url 'memorabilia:delete_collectible' object.collection.id object.id as the_url %}
            {% include "memorabilia/navitem.html" with link=the_url label="Delete Collectible" %}

            {% url 'memorabilia:create_photo_match' object.collection.id object.id as the_url %}
            {% include "memorabilia/navitem.html" with link=the_url label="Add Photo Match" %}
        {% endif %}
    {% endif %}
{% endblock page_navigation %}

{% block breadcrumb %}
    {% url 'memorabilia:list_collections' as the_url %}
    {% include 'memorabilia/breadcrumb.html' with url=the_url label="Collections" %}
    {% url 'memorabilia:collection' collectible.collection.id as the_url %}
    {% include 'memorabilia/breadcrumb.html' with url=the_url label=collectible.collection.title %}
    {% include 'memorabilia/breadcrumb.html' with label=collectible.title %}
{% endblock breadcrumb %}

{% block content %}
<h1 class="mb-6 text-4xl text-center font-extrabold tracking-tight leading-none md:text-5xl lg:text-6xl">{{ object.title }}</h1>
<div class="grid grid-cols-1 md:grid-cols-2 gap-4 pb-4">
    <div class="grid gap-4 w-full">
        <div class="mx-auto">
            {% include "memorabilia/elements/modal.html" with image_url=collectible.primary_image %}
        </div>
        <div class="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {% for image in object.images.all %}
                {% if image.primary == False %}
                    {% getmediaurl image as image_url %}
                    {% include "memorabilia/elements/modal.html" with image_url=image_url %}
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="w-full relative overflow-x-auto">
        <table class="table-auto sm:rounded-lg border shadow-md w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
            <tbody>
                {% include 'memorabilia/tablerow.html' with label='League' value=collectible.league %}
                {% include 'memorabilia/tablerow.html' with label='Brand' value=collectible.brand %}
                {% include 'memorabilia/tablerow.html' with label='Size' value=collectible.size %}
                {% include 'memorabilia/tablerow.html' with label='Player' value=collectible.player %}
                {% include 'memorabilia/tablerow.html' with label='Team' value=collectible.team %}
                {% include 'memorabilia/tablerow.html' with label='Number' value=collectible.number %}
                {% include 'memorabilia/tablerow.html' with label='Season' value=collectible.season %}
                {% include 'memorabilia/tablerow.html' with label='Description' value=collectible.description %}
                {% include 'memorabilia/tablerow.html' with label='Usage Type' value=collectible.usage_type %}
                {% include 'memorabilia/tablerow.html' with label='Game Type' value=collectible.game_type %}
                <!-- {% include 'memorabilia/tablerow.html' with label='Collection' value=collectible.collection %} -->
                <!-- {% include 'memorabilia/tablerow.html' with label='For Sale' value=collectible.for_sale %} -->
                <!-- {% include 'memorabilia/tablerow.html' with label='For Trade' value=collectible.for_trade %} -->
                {% if object.for_sale %}
                    {% include 'memorabilia/tablerow.html' with label='Asking Price' value=collectible.asking_price %}
                {% endif %}
                {% if object.for_trade %}
                    {% include 'memorabilia/tablerow.html' with label='Looking for' value=collectible.looking_for %}
                {% endif %}    
            </tbody>
        </table>
        
    </div>
</div>

{% if object.photomatches.all.count > 0 %}
<h2 class="mb-6 text-2xl text-center font-extrabold tracking-tight leading-none md:text-3xl lg:text-4xl">Photo matches</h2>
<div class="container flex flex-row gap-4 w-full justify-start">
    {% for image in object.photomatches.all %}
        {% getmediaurl image as image_url %}
        {% include 'memorabilia/photomatch_card.html' with image_url=image_url %}
    </div>
    {% endfor %}
</div>
{% endif %}

{% endblock content %}

memorabilia/templates/memorabilia/collectible_form.html
{% extends 'memorabilia/base.html' %}
{% load memorabilia_extras %}

{% block head_title %}
    {{ title }}
{% endblock head_title %}

{% block extrahead %}
    {{ image_formset.media }}
{% endblock extrahead %}

{% block navigation %}
    {% if user.is_authenticated %}
        {% if user.id == collection.owner_uid or user.is_superuser %}
            {% url 'memorabilia:edit_collection' collection.id as the_url %}
            {% include "memorabilia/navitem.html" with link=the_url label="Edit Collection" %}

            {% url 'memorabilia:delete_collection' collection.id as the_url %}
            {% include "memorabilia/navitem.html" with link=the_url label="Delete Collection" %}

            {% url 'memorabilia:create_collectible' collection.id as the_url %}
            {% include "memorabilia/navitem.html" with link=the_url label="Add Collectible" %}
        {% endif %}
    {% endif %}
{% endblock navigation %}

{% block breadcrumb %}
    {% url 'memorabilia:list_collections' as the_url %}
    {% include 'memorabilia/breadcrumb.html' with url=the_url label="Collections" %}
    {% if collectible %}
        {% url 'memorabilia:collection' collectible.collection.id as the_url %}
        {% include 'memorabilia/breadcrumb.html' with url=the_url label=collectible.collection.title %}
        {% url 'memorabilia:collectible' collection_id=collectible.collection.id pk=collectible.id as the_url %}
        {% include 'memorabilia/breadcrumb.html' with url=the_url label=collectible.title %}
    {% else %}
        {% url 'memorabilia:collection' collection.id as the_url %}
        {% include 'memorabilia/breadcrumb.html' with url=the_url label=collection.title %}
    {% endif %}
{% endblock breadcrumb %}

{% block content %}
<h1 class="mb-6 text-4xl text-center font-extrabold tracking-tight leading-none md:text-5xl lg:text-6xl">{{ title }}</h1>

<form method="post" enctype="multipart/form-data" novalidate class="bg-white rounded-lg shadow p-4">
    {% csrf_token %}
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 pb-4">
    <!-- Left Column - Images -->
    <div class="grid gap-4 w-full">
        <div class="bg-white p-4 rounded-lg shadow">
            <h2 class="text-xl font-semibold mb-4">Images</h2>
            {% include 'memorabilia/flickr_album_widget.html' with formset=image_formset %}
        </div>
    </div>

    <!-- Right Column - Form Fields -->
    <div class="w-full">
            {% if form.non_field_errors %}
                <div class="bg-red-50 border-l-4 border-red-500 p-4 mb-4">
                    {% for error in form.non_field_errors %}
                        <p class="text-red-700">{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}

            <table class="table-auto sm:rounded-lg border shadow-md w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">            
                {% for field in form.visible_fields %}
                    {% if field.name != 'primary_image' %}
                        <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-t border-b dark:border-gray-700">
                            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">{{ field.label_tag }}</th>
                            <td class="px-6 py-2">
                                {{ field }}
                                {% if field.name == 'league' %}
                                    <datalist id="league-list">
                                        {% for l in leagues %}
                                            <option value="{{ l.key }}" label="{{ l.name }}"></option>
                                        {% endfor %}
                                    </datalist>
                                {% endif %}
                                {% if field.name == 'team' %}
                                    <datalist id="team-list"></datalist>
                                    <script>
                                      (function() {
                                        function fillTopOptionOnTab(e, inputEl, listId) {
                                          if (e.key !== 'Tab') return;
                                          const list = document.getElementById(listId);
                                          if (!list) return;
                                          const q = (inputEl.value || '').trim().toLowerCase();
                                          if (!q) return;
                                          const opts = Array.from(list.options || []);
                                          // Prefer startsWith match; fallback to contains
                                          let match = opts.find(o => (o.value || '').toLowerCase().startsWith(q));
                                          if (!match) match = opts.find(o => (o.value || '').toLowerCase().includes(q));
                                          if (match) {
                                            inputEl.value = match.value;
                                            // Do not prevent default so Tab still moves focus forward
                                            return true;
                                          }
                                          return false;
                                        }
                                        function populateTeams(leagueVal) {
                                          const list = document.getElementById('team-list');
                                          if (!list) return;
                                          list.innerHTML = '';
                                          if (!leagueVal) return;
                                          fetch(`{% url 'memorabilia:get_teams' %}?league=${encodeURIComponent(leagueVal)}`)
                                            .then(r => r.json())
                                            .then(data => {
                                              (data.teams || []).forEach(name => {
                                                const opt = document.createElement('option');
                                                opt.value = name;
                                                list.appendChild(opt);
                                              });
                                            })
                                            .catch(() => {});
                                        }
                                        // On load
                                        document.addEventListener('DOMContentLoaded', function() {
                                          const leagueInput = document.querySelector('[name="league"]');
                                          const teamInput = document.querySelector('[name="team"]');
                                          if (leagueInput) {
                                            populateTeams(leagueInput.value);
                                            leagueInput.addEventListener('input', function(e) {
                                              populateTeams(e.target.value);
                                            });
                                            leagueInput.addEventListener('keydown', function(e) {
                                              const filled = fillTopOptionOnTab(e, leagueInput, 'league-list');
                                              if (filled) {
                                                // Ensure teams datalist updates before focus leaves
                                                populateTeams(leagueInput.value);
                                              }
                                            });
                                          }
                                          if (teamInput) {
                                            teamInput.addEventListener('keydown', function(e) {
                                              fillTopOptionOnTab(e, teamInput, 'team-list');
                                            });
                                          }
                                          // If team has a value and list empty, keep it; options populate lazily
                                        });
                                      })();
                                    </script>
                                {% endif %}
                                {% if field.help_text %}
                                    <p class="text-xs text-gray-500 mt-1">{{ field.help_text }}</p>
                                {% endif %}
                                {% if field.errors %}
                                    <div class="form-errors">{{ field.errors }}</div>
                                {% endif %}
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                {# Ensure collection is submitted even though it's not rendered visibly #}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
            </table>

            <div class="flex justify-end space-x-4 mt-6">
                <button
                    type="button"
                    onclick="history.back()"
                    class="px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                    Cancel
                </button>
                <button
                    type="submit"
                    class="px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                    Save Changes
                </button>
            </div>
    </div>
    </div>
</form>
{% endblock content %}

memorabilia/templates/memorabilia/collection_card.html
{% load memorabilia_extras %}

<div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <a href="{{ link }}">

        <div class="flex w-96 items-center justify-center h-72 bg-gray-100 rounded dark:bg-gray-700">
            {% if image %}
            <img class="rounded-t-lg object-contain w-full h-full" src="{{ image }}" alt="" />
            {% else %}
            <svg class="w-10 h-10 text-gray-200 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 20">
                <path d="M14.066 0H7v5a2 2 0 0 1-2 2H0v11a1.97 1.97 0 0 0 1.934 2h12.132A1.97 1.97 0 0 0 16 18V2a1.97 1.97 0 0 0-1.934-2ZM10.5 6a1.5 1.5 0 1 1 0 2.999A1.5 1.5 0 0 1 10.5 6Zm2.221 10.515a1 1 0 0 1-.858.485h-8a1 1 0 0 1-.9-1.43L5.6 10.039a.978.978 0 0 1 .936-.57 1 1 0 0 1 .9.632l1.181 2.981.541-1a.945.945 0 0 1 .883-.522 1 1 0 0 1 .879.529l1.832 3.438a1 1 0 0 1-.031.988Z"/>
                <path d="M5 5V.13a2.96 2.96 0 0 0-1.293.749L.879 3.707A2.98 2.98 0 0 0 .13 5H5Z"/>
            </svg>
            {% endif %}
        </div>
    </a>
    <div class="p-5">
        <a href="{{ link }}">
            <h5 class="mb-2 text-center text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ label }}</h5>
            <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{ description }}</p>
        </a>
        <div class="flex justify-end gap-4">
            <div class="font-medium dark:text-white">
                <div>owned by {{owner_username}}</div>
                <div class="text-sm text-gray-500 dark:text-gray-400"></div>
            </div>
            <img class="w-10 h-10 rounded-full" src="{% get_user_avatar_url collection.owner_email %}" alt="">
        </div>
    </div>
</div>

memorabilia/templates/memorabilia/collection_detail.html
{% extends 'memorabilia/base.html' %}
{% load static %}
{% load memorabilia_extras %}

{% block page_css %}
    <link rel="stylesheet" href="{% static 'memorabilia/collection-detail.css' %}">
{% endblock page_css %}

{% block page_navigation %}
    {% if user.is_authenticated %}
        {% if user.id == collection.owner_uid or user.is_superuser %}
            {% url 'memorabilia:edit_collection' collection.id as the_url %}
            {% include "memorabilia/navitem.html" with link=the_url label="Edit Collection" %}

            {% url 'memorabilia:delete_collection' collection.id as the_url %}
            {% include "memorabilia/navitem.html" with link=the_url label="Delete Collection" %}

            {% url 'memorabilia:create_collectible' collection.id as the_url %}
            {% include "memorabilia/navitem.html" with link=the_url label="Add Collectible" %}

            {% url 'memorabilia:bulk_edit_collectibles' collection.id as the_url %}
            {% include "memorabilia/navitem.html" with link=the_url label="Edit All Collectibles" %}
        {% endif %}
    {% endif %}
{% endblock page_navigation %}

{% block breadcrumb %}
    {% url 'memorabilia:list_collections' as the_url %}
    {% include 'memorabilia/breadcrumb.html' with url=the_url label="Collections" %}
    {% include 'memorabilia/breadcrumb.html' with label=collection.title %}
{% endblock breadcrumb %}

{% block content %}
    {% if collection.image %}
        {% getmediaurl collection.image as image_url %}
    {% else %}
        {% getmediaurl collection.image_link as image_url %}
    {% endif %}
    <section style="background-image: url('{{ image_url }}');" class="rounded-lg bg-center bg-cover bg-no-repeat bg-gray-500 bg-blend-multiply">
        <div class="px-4 mx-auto max-w-screen-xl text-center py-24 lg:py-56">
            <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-white md:text-5xl lg:text-6xl">{{ collection.title }}</h1>
            <p class="mb-8 text-lg font-normal text-gray-300 lg:text-xl sm:px-16 lg:px-48">{{ collection.description }}</p>
        </div>
    </section>

    <div class="flex flex-wrap gap-4 py-4 justify-evenly">
        {% for collectible in collection.collectible_set.all %}
            {% url 'memorabilia:collectible' collection.id collectible.id as the_url %}
            {% getmediaurl collectible.get_primary_image as image_url %}
            {% include "memorabilia/collectible_card.html" with link=the_url label=collectible.title image=image_url %}
        {% endfor %}
    </div>    

{% endblock content %}

memorabilia/templates/memorabilia/navitem.html
<li>
    <a href="{{ link }}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">{{ label }}</a>
</li>

memorabilia/templates/memorabilia/photomatch_detail.html
{% extends 'memorabilia/base.html' %}

{% block page_navigation %}
    {% if user.is_authenticated %}
        {% if user.id == object.collectible.collection.owner_uid or user.is_superuser %}
            {% url 'memorabilia:edit_photo_match' object.collectible.collection.id object.collectible.id object.id as the_url %}
            {% include "memorabilia/navitem.html" with link=the_url label="Edit" %}

            {% url 'memorabilia:delete_photo_match' object.collectible.collection.id object.collectible.id object.id as the_url %}
            {% include "memorabilia/navitem.html" with link=the_url label="Delete" %}
        {% endif %}
    {% endif %}
{% endblock page_navigation %}

{% block breadcrumb %}
<div class="crumb"><a href="{% url 'memorabilia:home' %}">Home</a></div>><div class="crumb"><a href="{% url 'memorabilia:list_collections' %}">Collections</a></div>><div class="crumb"><a href="{% url 'memorabilia:collection' object.collectible.collection.id %}">{{ object.collectible.collection }}</a></div>><div class="crumb"><a href="{% url 'memorabilia:collectible' object.collectible.collection.id object.collectible.id %}">{{ object.collectible }}</a></div>
{% endblock breadcrumb %}


{% block content %}
    <p>{{ object.collectible }}</p>
    <p>{{ object.game_date }}</p>
    {% if object.image|length > 0 %}
    <p><img src='{{ MEDIA_URL }}{{ object.image }}' /></p>
    {% endif %}
{% endblock content %}